env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

    GH_TOKEN: "ENCRYPTED[!59def97ae0387ce36715d7586f10330b2896b7f6ccffb8c59002756eb85085465ddc8e18f7758e66108354160073391c!]"

task:
  name: Build DoraCore Kernel
  timeout_in: 2h
  only_if: $CIRRUS_REPO_OWNER == 'DoraCore-Projects'
  container:
    image: dopaemon/doracore:latest
    cpu: 4
    memory: 6G

  build_script:
    - bash run.sh canary
