name: ElectroKernel Canary
on:
  workflow_dispatch:

jobs:
   build:
    runs-on: ubuntu-20.04

    steps:
    - name: setting configurasi
      uses: actions/checkout@v3

    - name: setup environment
      run: |
          sudo apt-get update -yq --fix-missing
          sudo apt-get install -yq git make bc bison \
          openssl curl zip kmod cpio flex libelf-dev \
          libssl-dev libtfm-dev wget device-tree-compiler \
          ca-certificates python3 python2 binutils \
          binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi \
          libghc-libyaml-dev libyaml-dev glibc-source sshpass

    - name: Setup git Store Password
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git config --global credential.helper store
          git config --global user.name "dopaemon"
          git config --global user.email "polarisdp@gmail.com"
          export FULL_TOKEN=${{ secrets.TOKEN_ONE }}${{ secrets.TOKEN_TWO }}${{ secrets.TOKEN_THREE }}
          git clone https://${FULL_TOKEN}@github.com/X-UI-Unofficial/Store-Passwd.git

    - name: Canary Build
      env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
      run: |
          bash run.sh canary
      shell: bash
